name: Prosemirror-To-Html

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.1"
          tools: php-cs-fixer, phpunit:7.5.20
      - name: Execute tests via PHPUnit
        run: phpunit
